# Generated by Django 2.1.5 on 2019-01-29 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hero_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='image',
            field=models.CharField(default='default.jpg', max_length=255),
            preserve_default=False,
        ),
    ]
